#!/usr/bin/env bash

#===================================================
# @author: Shashank Singh
#
# Script to only enable eDP-1 and disable the rest
#===================================================

xrandr \
  --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
  --output HDMI-1 --off
